project:
  type: website
  output-dir: .

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/envinatu
      - icon: twitter
        href: https://twitter.com/nvinatu
        
 #   background: light
    logo: images/envinatu1.png
    logo-alt: "Envinatu logo."
    cover-image: "images/envinatu1.png"
  #  title: false
 #   collapse-below: lg
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Biología"
        href: "https://envinatu.github.io/biologia/"
      - text: "Química"
        href: "https://envinatu.github.io/quimica/"
      - text: "Hidrología"
        href: "https://envinatu.github.io/hidrología"
      - text: "Educación"
        href: "https://envinatu.github.io/pedagogia"
      - text: "Rubick"
        href: "https://envinatu.github.io/rubick"        
      - text: "Blog"
        href: "https://envinatu.github.io/blog"
      - text: "Sobre Mi"
        href: "https://envinatu.github.io/amores"  

  back-to-top-navigation: true
  search: true
  page-footer:
    left: |
      <div style="display:inline;">© <script>document.write(new Date().getFullYear());</script> | <a href="https://github.com/envinatu">ENVINATU</a></div>
    center: 
        - icon: linkedin
          href: https://www.linkedin.com/envinatu
          aria-label: Marcelo Amores LinkedIn
        - icon: github
          href: https://github.com/envinatu
          aria-label: Envinatu GitHub
        - icon: x
          href: https://x.com/nvinatu
          aria-label: Quarto X
        - icon: youtube
          href: https://youtube.com/envinatu
          aria-label: Envinatu YouTube
        - icon: envelope
          href: mailto:contacto.envinatu@gmail.com
          aria-label: Email Us
     
    right: |
      Built with <a href="https://quarto.org/">Quarto</a>.

format:
  html:
 #   theme: cosmo
 #   css: styles.css
    theme:
      light:
        - cosmo #litera # morph # sketchy # default #spacelab # default # cosmo # spacelab sandstone
        - C:/Users/PC/My Drive/CIENCIAS/comp_files/amores-r4.scss
      dark:
        - solar # darkly # cyborg # slate # superhero
        - C:/Users/PC/My Drive/CIENCIAS/comp_files/amores-r4.scss
    include-after-body: C:/Users/PC/My Drive/CIENCIAS/comp_files/footer.html
editor: visual

